<?php
/**
 * @var $block \Rbj\CustomerTab\Block\Adminhtml\CustomerEdit\Tab\View
 */
?>
 
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Assign Store And Role') ?></span>
    </div>
        <div class="field email required">
            <label class="label" for="email">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="email" id="email" value=""
                       title="<?= $block->escapeHtml(__('Email')) ?>"
                       data-role="email"
                       class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
</div>