<!--<span class="addtofavoriteorder-button">
 <button type="submit" id="addto-favorite" title="Add To Favorite" class="action primary" product_id= "<?= /* @escapeNotVerified */
$block->getProductId(); ?>" product_name ="<?= /* @escapeNotVerified */
$block->getProductName(); ?>" favoriteorder_url ="<?= /* @escapeNotVerified */
$block->getUrl("favoriteorder/index/index"); ?>" >
        <span>Add To Favorite</span>
    </button>
</span>  -->