


<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "/checkout/cart/updateItemQty"}
          }'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart products-grid table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar" data-attribute="cart-products-toolbar-top">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>

<!--remove--->
             
 
<button href="#"
   class="action primary movetostore move-<?= $block->getProductId(); ?>" 
   title="<?= $block->escapeHtmlAttr(__('Move to Store Order')) ?>"
   aria-label="<?= $block->escapeHtmlAttr(__('Move to Store Ordert')) ?>"
   data-action="move-to-storeorder"
   item_id="cart-<?= $block->getItemId(); ?>-qty"
   product_id ="<?= $block->getProductId(); ?>"
   id="move-<?= $block->getProductId(); ?>"
   role="button">
    <span><?= $block->escapeHtml(__('Move to Store Order')) ?></span>
</button>    
<!--remove--->


        <div id="shopping-cart-table" class="cart items data table products grid items product-items" data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear", "updateCartActionContainer": "#update_cart_action_container"}}'>
            
                <ol class="products grid items product-items">
                <?php foreach ($block->getItems() as $_item): ?>
                     <li class="item product product-item">
                    <?= $block->getItemHtml($_item) ?>

                
                    <button type="submit" name="update_cart_action" data-cart-item-update="" value="update_qty"
                            title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>" class="action update">
                         <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
                    </button>
                     
                </li>
                <?php endforeach ?>
            </ol>
            
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar" data-attribute="cart-products-toolbar-bottom">
                <?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update none">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

