<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

//get ordered product

$storeProduct = $block->getLayout()->createBlock('Tychons\Storeorder\Block\StoreOrderProduct');
$orderedproduct = $storeProduct->getOrderedProduct();

//end ordered product

$_item = $block->getItem();

$product = $_item->getProduct();

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<div class="item-actions">
    <div colspan="4">
        <div class="toolbars">
            <?= /* @escapeNotVerified */
            $block->getActions($_item) ?>
        </div>
    </div>


    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
            <a href="<?= /* @escapeNotVerified */
            $block->getProductUrl() ?>"
               title="<?= $block->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= /* @escapeNotVerified */
                        $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()): ?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */
                                    $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?= /* @escapeNotVerified */
                        $message['type'] ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */
                        __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */
                    ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */
                    $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */
                    $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */
                            __("What's this?") ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>

        <!--Purchase Order date -->
        <?php

        $productId = $_item->getProductId();

        if (isset($orderedproduct[$productId])): ?>
            <div class="last-purchased-date">
                <span class="last-pur-span">Last Purchased Date :</span>
                <span id="last-pur-dat"><?= /* @escapeNotVerified */
                    $orderedproduct[$productId] ?></span>
            </div>
        <?php else: ?>
            <div class="last-purchased-date">
                <span class="last-pur-span">Last Purchased Date :</span>
                <span id="last-pur-dat">Not available</span>
            </div>
        <?php endif; ?>
        <!--Purchase Order date -->

        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty:')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= /* @escapeNotVerified */
                $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */
                        __('Qty:') ?></span>
                </label>
                <div class="control" data-bind="scope: 'qty_change'">
                    <input id="cart-<?= /* @escapeNotVerified */
                    $_item->getId() ?>-qty"
                           name="cart[<?= /* @escapeNotVerified */
                           $_item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                           value="<?= /* @escapeNotVerified */
                           $block->getQty() ?>"
                           class="qty"
                           type="text"
                           size="4"
                           min="1"
                           value="1"
                           value="<?= /* @escapeNotVerified */
                           $block->getProductDefaultQty() * 1 ?>"
                           title="<?= $block->escapeHtml(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>

                    <button class="qty-right" data-bind="click: increaseQty">+</button>
                    <button class="qty-left" data-bind="click: decreaseQty">-</button>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <div class="item-actions">
        <div colspan="4">
            <div class="actions-toolbar">
                <?= /* @escapeNotVerified */
                $block->getActions($_item) ?>
            </div>
        </div>
    </div>
</tbody>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty_change": {
                        "component": "Tychons_Rushorder/js/qty_change",
                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                    }
                 }
            }
        }
    }






</script>