<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \ISN\PaymentAccount\Block\Info\AccountPayment
 */
?>
<dl class="payment-method purchase order" id="order-payment-information">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <?php if ($block->getInfo()->getPoNumber()): ?>
        <strong><?= $block->escapeHtml(__('Purchase Order Number')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
        <?php endif; ?>
    </dd>
    <dd class="content">
        <?php if ($block->isCurrencyDifferent()): ?>
            <strong><?= $block->escapeHtml(__('Charged off the company credit')) ?></strong>
            <span class="number"><?= /* @noEscape */ $block->getChargedAmount() ?></span>
        <?php endif; ?>
    </dd>
</dl>
