<div id="documents">
    <ul>
        <li>Invoices</li>
        <li class="k-state-active">Statements</li>
        <li>Credits</li>
        <li>Open Orders</li>
        <li>Backorders</li>
    </ul>
    <div id="invoices"></div>
    <div id="statements"><div></div></div>
    <div id="credits"><div></div></div>
    <div id="orders"><div></div></div>
    <div id="backorders"><div></div></div>
</div>
