<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \ISN\PaymentAccount\Block\Info\AccountPayment
 */
?>
<?php
if ($block->getInfo()->getPoNumber()) {
    echo $block->escapeHtml(__('Purchase Order Number: %1', $block->getInfo()->getPoNumber()));
    echo '{{pdf_row_separator}}';
}
echo $block->escapeHtml(__('Charged off the company credit: %1', $block->getChargedAmount()));
?>
{{pdf_row_separator}}
